refactor ProcessFactory to help debugging
eclipse-cdt/cdt pull request #191
Opened 2022-12-04 02:19 UTC by xu-chiheng

2022-12-05 20:06 UTC, jonahgraham requested changes

2022-12-05 20:06 UTC, jonahgraham commented on core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> +			debug();
I am not keen on having this run all the time. Can you consider putting this behind a trace flag or simply commenting out this line?

```suggestion
			// Uncomment the next line, step over debug() to get detailed info on what is being launched.
			// var debug = debug();
```

2022-12-05 20:06 UTC, jonahgraham commented on core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> +				// environmentB.containsKey(key)
Remove commented out code.
```suggestion
```

2022-12-05 20:23 UTC, xu-chiheng commented
On Tue, Dec 6, 2022 at 4:07 AM Jonah Graham ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> <https://github.com/eclipse-cdt/cdt/pull/191#discussion_r1039008309>:
>
> > @@ -33,6 +40,94 @@ public class ProcessFactory {
>
>  	private boolean hasSpawner;
>
>  	private Runtime runtime;
>
>
>
> +	private static TreeMap<String, String> newEmptyEnvironment() {
>
> +		TreeMap<String, String> environment;
>
> +		if (Platform.getOS().equals(Platform.OS_WIN32)) {
>
>
> What is the purpose of case insensitive comparator only on windows? I
> assume it is to make Path and PATH appear next to each other when
> iterating? However it will leave both Path and PATH in the map which won’t
> represent what happens in the process
>
Wrong, the purpose is to treat Path and PATH as the same key.


> ------------------------------
>
> In
> core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> <https://github.com/eclipse-cdt/cdt/pull/191#discussion_r1040039922>:
>
> >  		public Process start() throws IOException {
>
>  			cmdarray = modifyCmdArrayIfFlatpak(cmdarray);
>
> +			debug();
>
>
> I am not keen on having this run all the time. Can you consider putting
> this behind a trace flag or simply commenting out this line?
> ⬇️ Suggested change
>
> -			debug();
>
> +			// Uncomment the next line, step over debug() to get detailed info on what is being launched.
>
> +			// var debug = debug();
>
> can be done, comment it out.

> ------------------------------
>
> In
> core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> <https://github.com/eclipse-cdt/cdt/pull/191#discussion_r1040040360>:
>
> > +						sb.append('+');
>
> +						sb.append(key);
>
> +						sb.append('=');
>
> +						sb.append(valueB);
>
> +						sb.append('\n');
>
> +					}
>
> +				} else {
>
> +					// removed
>
> +					sb.append('-');
>
> +					sb.append(key);
>
> +					sb.append('=');
>
> +					sb.append(valueA);
>
> +					sb.append('\n');
>
> +				}
>
> +			} else {
>
> +				// environmentB.containsKey(key)
>
>
> Remove commented out code.
> ⬇️ Suggested change
>
> -				// environmentB.containsKey(key)
>
> This is just a comment for better reading the code .

2022-12-05 20:37 UTC, jonahgraham commented on core/org.eclipse.cdt.core.native/src/org/eclipse/cdt/utils/spawner/ProcessFactory.java
> +		if (Platform.getOS().equals(Platform.OS_WIN32)) {
Please disregard my incorrect comment here.

2022-12-05 22:07 UTC, jonahgraham approved these changes
LGTM, let me know when you are finished pushing commits to this PR.

2022-12-06 18:02 UTC, xu-chiheng commented
On Tue, Dec 6, 2022 at 6:07 AM Jonah Graham ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> LGTM, let me know when you are finished pushing commits to this PR.
>
already finished.

2022-12-06 18:20 UTC, jonahgraham commented
On Tue, 6 Dec 2022 at 13:02, 徐持恒 Xu Chiheng ***@***.***>
wrote:

> On Tue, Dec 6, 2022 at 6:07 AM Jonah Graham ***@***.***>
> wrote:
>
> > ***@***.**** approved this pull request.
> >
> > LGTM, let me know when you are finished pushing commits to this PR.
> >
> already finished.
>

😀


> Message ID: ***@***.***>
>

2022-12-06 18:20 UTC, merged