Allows launch config to override launch target connection type
eclipse-cdt/cdt pull request #625
Opened 2023-11-21 11:30 UTC by betamaxbandit

When launching a GDB debug session using the Launch Bar and a Launch Target, now the launch takes into account a REMOTE_TCP value in the launch configuration before considering the type of the Launch Target.

Improves the change submitted in:
Bug 547881 - Allow targets to set ATTR_REMOTE_TCP

Fixes issue #622

2023-11-21 11:59 UTC, betamaxbandit commented
Hi @jonahgraham ,

I'm not sure how to test this!
Either a manual UI test could be done or a JUnit added.
Manual test: I tried a manual test but didn't get past trying to launch it [1]

JUnit: I've investigated this a bit and it looks doable, but not sure whether it's worth it [2]

Do you have any advice please?

[1] Manual test
Using CDT New C/C++ Project wizard, created a CMake Project.

In Preferences > Core Build Toolchains, the auto detected GCC is shown:
Core Build Toolchains
  Available Toolchains
    Type    Name                                         OS     Arch
    GCC     win32 x86_64: C:\msys64\mingw64\bin\gcc.exe  win32  x86_64

In Preferences > CMake, I downloaded an example CMake toolchain file (MSYS2.cmake) from internet and added it to the toolchain above.

CMake
  Toolchain Files
    Toolchain File    Toolchain
      MSYS2.cmake     win32 x86_64: C:\msys64\mingw64\bin\gcc.exe

I created a new Generic Target launch target:
  Name: gen
  Operating System: win32
  CPU Architecture: x86_64

I built the project. An executable was successfully generated.

Click Launch Bar Run (Launch in Run mode) button
Console: No action specified. Skipping.


[2] Junit
I noticed org.eclipse.cdt.tests.dsf.gdb.launching.TestLaunchDelegate. I can extend this class and override 

  GdbLaunchDelegate.getLaunch(ILaunchConfiguration, String)

And then set the launch target using GdbLaunch.setLaunchTarget(ILaunchTarget)
      
  Then setup a launch configuration which includes IGDBLaunchConfigurationConstants.ATTR_REMOTE_TCP attr set to true.
  
Then launch and inspect whether the FinalLaunchSequence.stepRemoteConnection(RequestMonitor) indeed attempts a isTcpConnection rather than a serial connect. [Not sure how to detect this]

2023-11-21 21:52 UTC, jonahgraham requested changes
This change lgtm - I can merge it after I branch which is in the new few days.

My feeling for a test here is that a lot of scaffolding is probably needed to automate this test. I suspect the dev effort required to do it for this change doesn't warrant it. But I think we should make sure that at least a manual test runs, even if it is just for the default case where the attribute is not in the launch already. From your [description](https://github.com/eclipse-cdt/cdt/pull/625#issuecomment-1820783394) it sounds like this has exposed other problems with the cmake integration. Some of them may already be [reported in this query](https://github.com/eclipse-cdt/cdt/issues?q=is%3Aissue+is%3Aopen+cmake)

2023-12-27 22:09 UTC, jonahgraham approved these changes
@betamaxbandit and I had a call about this and we verified that the behavior wasn't regressing as requested. So this is good to go. I am going to rebase the change to make sure there are no conflicts/issues

2023-12-27 23:42 UTC, merged

2023-12-27 23:42 UTC, jonahgraham commented
Thanks @betamaxbandit for this fix.