Bug 580015: add support for multiple bin parsers
eclipse-cdt/cdt pull request #75
Opened 2022-09-26 19:42 UTC by betamaxbandit

Added ability to return a list of binary parser IDs, rather than a single ID. This supports build configurations that have multiple binaries with for example cross toolchains.

Change-Id: I1b7e47bf6a86bbd9f1c6b9646d008bac9479417d

2022-09-26 20:01 UTC, jonahgraham requested changes
This is migrated from https://git.eclipse.org/r/c/cdt/org.eclipse.cdt/+/194075 - so the comments from it are migrated to it.

2022-09-26 20:01 UTC, jonahgraham commented on core/org.eclipse.cdt.core/.settings/.api_filters
> +    <resource path="src/org/eclipse/cdt/core/build/ICBuildConfiguration.java" type="org.eclipse.cdt.core.build.ICBuildConfiguration">
With CDT 11 we can just make this a new major version of the bundle and not have to have this API filter.

WDYT?

2022-09-26 20:01 UTC, jonahgraham commented on core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/build/ICBuildConfiguration.java
> +	default List<String> getBinaryParserIds() throws CoreException {
With a new major revision (CDT 11) this method shouldn't have a default anymore.

2022-09-28 22:24 UTC, betamaxbandit commented
Hi @jonahgraham ,
Can you review my changes to the actual code please? Note I'm still working on the tests (TestICBuildConfiguration), but ran out of time today.

2022-09-29 16:45 UTC, jonahgraham requested changes
I didn't look at tests, other than the location of them. Let me know if you need a suggestion of where they should go. It may also be appropriate to leave them there if there isn't anywhere better already.

2022-09-29 16:45 UTC, jonahgraham commented on core/org.eclipse.cdt.core.tests/META-INF/MANIFEST.MF
> + org.eclipse.cdt.build.gcc.core
I think this dependency is a problem - not sure core.tests should depend on something not in cdt core.

2022-09-29 16:45 UTC, jonahgraham commented on core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/build/ICBuildConfiguration.java
> +	@Deprecated(since = "8.0")
Delete this, don't just deprecate it.

2022-09-29 16:45 UTC, jonahgraham commented on core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/build/IToolChain.java
> +	@Deprecated(since = "8.0")
Delete this, don't just deprecate it.

2022-09-29 16:47 UTC, jonahgraham commented on core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/build/ICBuildConfiguration.java
> +	@Deprecated(since = "8.0")
The reason to bump the major version for this is precisely so we can delete the API without deprecation.
https://github.com/eclipse-cdt/cdt/blob/main/doc/org.eclipse.cdt.doc.isv/guide/deprecated_API_removals.html needs to be updated to list the deprecation + mitigation.

2022-09-29 16:48 UTC, jonahgraham commented on core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/build/ICBuildConfiguration.java
> +	@Deprecated(since = "8.0")
(should have read ) needs to be updated to list the **removal** + mitigation.

2022-11-07 22:38 UTC, jonahgraham commented
@betamaxbandit Will you have time to look at this this week? It would be ideal to get this done in time for M3 which is 14 Nov.

2022-11-07 23:04 UTC, betamaxbandit commented
> @betamaxbandit Will you have time to look at this this week? It would be ideal to get this done in time for M3 which is 14 Nov.

Hi Jonah,

Yes, I'll try. Thanks for the reminder.

2022-11-14 20:02 UTC, jonahgraham commented
There is a compilation failure now BTW:

```sh
Error:  Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.5:compile (default-compile) on project org.eclipse.cdt.docker.launcher: Compilation failure: Compilation failure: 
Error:  /home/runner/work/cdt/cdt/launch/org.eclipse.cdt.docker.launcher/src/org/eclipse/cdt/internal/docker/launcher/ui/launchbar/ContainerGCCToolChain.java:[70] 
Error:  	public class ContainerGCCToolChain extends PlatformObject implements IToolChain, IToolChain2 {
Error:  	             ^^^^^^^^^^^^^^^^^^^^^
Error:  The type ContainerGCCToolChain must implement the inherited abstract method IToolChain.getBinaryParserIds()
Error: [ERROR] 1 problem (1 error)
Error:  -> [Help 1]
```

2022-11-14 20:17 UTC, betamaxbandit commented
Hi @jonahgraham ,
I didn't mean to do that. Still getting used to the github i/f. I was trying to rebase on main, but not sure I did it correctly.

2022-11-15 14:16 UTC, betamaxbandit commented
> Don't worry about the code cleanliness checks fails - there is a proposal to automate this in #166

Hi Jonah, ok, I won't.
I fixed the remaining problem which was the junit tests were failing. All tests pass now :-)

2022-11-15 14:49 UTC, jonahgraham requested changes
This looks fine, just needs a N&N entry about the improved API.

In https://github.com/eclipse-cdt/cdt/blob/main/NewAndNoteworthy/CDT-11.0.md below `Binary Parser code uses AutoCloseable` section

```
## Core Build tool chains can now return multiple binary parsers

The `ICBuildConfiguration` and `IToolChain` interfaces now have a method, `getBinaryParserIds` that allows a build configuration or tool chain to return multiple binary parsers.

See https://github.com/eclipse-cdt/cdt/pull/75

```

2022-11-15 15:19 UTC, jonahgraham requested changes
LGTM - needs the code cleanliness sorted out. I would like to use this PR to test #166 if I can get that done.

2022-11-15 15:31 UTC, betamaxbandit commented
> LGTM - needs the code cleanliness sorted out. I would like to use this PR to test #166 if I can get that done.

Oh ok. I don't really understand the actual cleanliness error. It says the following files are missing, but those file don't exist for me locally - only org.eclipse.jdt.core.prefs. Am I expected to generate them?

	build/org.eclipse.cdt.build.gcc.core.tests/.settings/org.eclipse.core.resources.prefs
	build/org.eclipse.cdt.build.gcc.core.tests/.settings/org.eclipse.jdt.launching.prefs
	build/org.eclipse.cdt.build.gcc.core.tests/.settings/org.eclipse.jdt.ui.prefs
	build/org.eclipse.cdt.build.gcc.core.tests/.settings/org.eclipse.pde.api.tools.prefs
	build/org.eclipse.cdt.build.gcc.core.tests/.settings/org.eclipse.pde.prefs

Do you want me to do anything for https://github.com/eclipse-cdt/cdt/issues/166 ?

2022-11-15 17:32 UTC, jonahgraham commented
> Do you want me to do anything for #166 ?

No.

If I can get #166 to work it will magically and automatically fix this PR. If not I will fix it up manually and merge it in a few days (ahead of RC1 on Monday)

2022-11-18 15:55 UTC, jonahgraham approved these changes

2022-11-18 15:55 UTC, merged

2022-11-18 16:22 UTC, betamaxbandit commented
Thanks for merging @jonahgraham