Adds capability to display warnings in LaunchBar Launch Config Dialog
eclipse-cdt/cdt pull request #879
Opened 2024-08-01 21:44 UTC by betamaxbandit

Add SWTBot to test that the Launch Configuration, when opened via the Launch Bar, displays a warning in the message area.

2024-08-02 01:40 UTC, jonahgraham commented
This looks like a great test @betamaxbandit

2024-08-05 20:37 UTC, betamaxbandit commented
Failing SWTBot test added.
Expected to fail with this message (as it has) until implementation added:

> Timeout after: 10000 ms.: Incorrect warning message; expected=This is a warning, actual=Edit the new launch configuration properties

2024-08-07 02:25 UTC, jonahgraham requested changes
I just noticed the copyright error and had a quick look at the code which lgtm. Please set ready for review when ready for full review.

2024-08-07 02:25 UTC, jonahgraham commented on launchbar/org.eclipse.launchbar.ui/src/org/eclipse/launchbar/ui/internal/dialogs/NewLaunchConfigEditPage.java
> + * Copyright (c) 2014, 2024 Renesas Electronics Europe and others.
Please don't change copyright ownership on files :-) The proper copyright holder listed should be the original one, with "and others" covering Renesas. (Same applies to all copyright blocks)

2024-08-07 21:10 UTC, betamaxbandit commented
Hi @jonahgraham , I've set this PR for review now. I don't think there's anything for me to do on it right now. Waiting for you.
(not sure how to get rid of the "Merging is blocked" banner above.

2024-08-14 12:02 UTC, betamaxbandit commented
Hi @jonahgraham, do I need to do anything on this? Are you able to review this please?

2024-09-12 21:16 UTC, jonahgraham approved these changes

2024-09-12 21:16 UTC, merged

2024-09-12 21:42 UTC, betamaxbandit commented
Thanks @jonahgraham